version: '3.8'

services:
  redis:
    image: redis:latest

  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"  # Puerto del contenedor expuesto
    depends_on:
      - redis
