version: '3.8'

services:
  redis:
    image: redis:latest

  django:
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./:/app
    expose:
      - "8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A backend worker -l INFO
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  