version: '3'

services:
  # redis:
  #   image: redis:latest

  application:
    container_name: sylabus-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /app/entrypoint.sh
    expose:
      - 8000
    environment: DEBUG=True
      POSTGRESS_LOCALLY=False
      ENVIRONMENT=production
      BASE_URL=${DJANGO_BASE_URL}
      SECRET_KEY=${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      DATABASE_URL_PRODUCTION=${DJANGO_DATABASE_URL}
      CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      SOCIAL_AUTH_ALLOWED_REDIRECT_URIS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000
      MAILERSEND_API_KEY=''
      MAILERSEND_FROM=info@trial-3vz9dlejq064kj50.mlsender.net
      CELERY_BROKER_URL=redis://localhost:6379
