# Generated by Django 4.2.4 on 2025-10-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='semestre_dictado',
            field=models.CharField(blank=True, choices=[('PS', 'Primer Semestre'), ('SS', 'Segundo Semestre'), ('AN', 'Anual'), ('IN', 'Indistinto')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.CharField(choices=[('PS', 'Primer Semestre'), ('SS', 'Segundo Semestre'), ('AN', 'Anual'), ('IN', 'Indistinto')], max_length=2),
        ),
    ]
