# Generated by Django 4.2.4 on 2025-10-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_asignatura_semestre_dictado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_lab_presencial',
            new_name='total_lab_presencial',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_lab_remoto',
            new_name='total_lab_remoto',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_practica_presencial',
            new_name='total_practica_presencial',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_practica_remoto',
            new_name='total_practica_remoto',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_teoria_presencial',
            new_name='total_teoria_presencial',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_teoria_remoto',
            new_name='total_teoria_remoto',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_teorico_practico_presencial',
            new_name='total_teorico_practico_presencial',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='semanal_teorico_practico_remoto',
            new_name='total_teorico_practico_remoto',
        ),
        migrations.AlterField(
            model_name='actividadreservada',
            name='descripcion',
            field=models.TextField(max_length=4000),
        ),
    ]
