# Generated by Django 4.2.4 on 2025-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_asignatura_semestre_dictado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadreservada',
            name='descripcion',
            field=models.TextField(max_length=4000),
        ),
    ]
