# Generated by Django 4.2.4 on 2025-10-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_actividadreservada_descripcion'),
        ('backend', '0004_rename_semanal_lab_presencial_asignatura_total_lab_presencial_and_more'),
    ]

    operations = [
    ]
