# Generated by Django 4.2.4 on 2025-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_merge_20251029_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='carga_rtf',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
