# Generated by Django 4.2.4 on 2025-11-25

from django.db import migrations, models


def column_exists(cursor, table_name, column_name, db_vendor):
    """Check if a column exists in a table, supporting both SQLite and PostgreSQL."""
    if db_vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns
    else:
        # PostgreSQL/MySQL
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone() is not None


def add_column_if_not_exists(apps, schema_editor):
    """Add columns only if they don't already exist."""
    connection = schema_editor.connection
    db_vendor = connection.vendor

    # Check and add dedicacion to backend_rol
    with connection.cursor() as cursor:
        if not column_exists(cursor, 'backend_rol', 'dedicacion', db_vendor):
            cursor.execute('ALTER TABLE "backend_rol" ADD COLUMN "dedicacion" varchar(2) NULL')

    # Check and add cargo to backend_rol
    with connection.cursor() as cursor:
        if not column_exists(cursor, 'backend_rol', 'cargo', db_vendor):
            cursor.execute('ALTER TABLE "backend_rol" ADD COLUMN "cargo" varchar(255) NULL')

    # Check and add nombre to backend_anioacademico
    with connection.cursor() as cursor:
        if not column_exists(cursor, 'backend_anioacademico', 'nombre', db_vendor):
            cursor.execute('ALTER TABLE "backend_anioacademico" ADD COLUMN "nombre" varchar(255) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_configuracion_nombre'),
    ]

    operations = [
        migrations.RunPython(add_column_if_not_exists, migrations.RunPython.noop),
    ]
