# Generated by Django 4.2.4 on 2025-11-25

from django.db import migrations, models


def add_column_if_not_exists(apps, schema_editor):
    """Add columns only if they don't already exist."""
    connection = schema_editor.connection

    # Check and add dedicacion to backend_rol
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'backend_rol' AND column_name = 'dedicacion'
        """)
        if not cursor.fetchone():
            cursor.execute('ALTER TABLE "backend_rol" ADD COLUMN "dedicacion" varchar(2) NULL')

    # Check and add cargo to backend_rol
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'backend_rol' AND column_name = 'cargo'
        """)
        if not cursor.fetchone():
            cursor.execute('ALTER TABLE "backend_rol" ADD COLUMN "cargo" varchar(255) NULL')

    # Check and add nombre to backend_anioacademico
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'backend_anioacademico' AND column_name = 'nombre'
        """)
        if not cursor.fetchone():
            cursor.execute('ALTER TABLE "backend_anioacademico" ADD COLUMN "nombre" varchar(255) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_configuracion_nombre'),
    ]

    operations = [
        migrations.RunPython(add_column_if_not_exists, migrations.RunPython.noop),
    ]
