# Generated by Django 4.2.4 on 2025-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_anioacademico_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='dedicacion',
            field=models.CharField(blank=True, choices=[('N', 'No exclusiva'), ('E', 'Exclusiva')], max_length=2, null=True),
        ),
    ]
