# Generated by Django 4.2.4 on 2025-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_anioacademico_nombre'),
    ]

    # Operations already applied to database - keeping empty to mark as complete
    operations = []
