# Generated by Django 4.2.17 on 2026-02-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_anioacademico_nombre_rol_cargo_alter_rol_dedicacion'),
    ]

    operations = [
        # Los campos ya fueron agregados en la migración 0008
        # Esta migración se mantiene vacía para marcarla como aplicada
    ]
