# Generated by Django 4.2.17 on 2026-02-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_anioacademico_nombre_rol_cargo_alter_rol_dedicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estandar',
            name='descriptores',
            field=models.ManyToManyField(blank=True, to='backend.descriptor'),
        ),
    ]
